#app
spring.application.name=product-service
server.port=8081

#fakestore API
fakestore.api.url=https://fakestoreapi.com

#user/order service URL(for JWT valitation config)
services.user-order.url=http://localhost:8080

#jwt
jwt.secret=${JWT_SECRET}

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration